prompt: "[Role]\n당신은 대규모 언어 모델이 작성한 '요약/요약형 콘텐츠'의 품질을 평가하는 전문가입니다.\n\n

[평가기준]\n다음 기준에\
  \ 따라 각 항목을 0~10 범위의 점수로 평가하세요.\n
  1. 핵심 포함 여부: 원문에서 중요한 정보가 모두 포함되었는가\n2. 불필요 정보 배제:\
  \ 사소하거나 관련 없는 내용이 제거되었는가\n3. 간결성: 불필요한 장황함 없이 간결하게 작성되었는가\n4. 논리적 흐름: 요약된 내용이 자연스럽게\
  \ 이어지는가\n5. 요청 수준 적합성: '세부/간략' 등 요구된 요약 수준에 맞는가\n\n
  
  [추가 평가 기준]\n\n
  1. 의미 왜곡 여부: 스크립트의\
  \ 발언이나 결정을 잘못 해석하거나 왜곡하지 않았는가? (최대 점수: 3.0) (가중치: 1.5) \n\n
  2. 사용자 입력 반영도: ‘회의 목적’,\
  \ ‘요약 수준’ 등 사용자 요구사항을 충실히 반영했는가? (최대 점수: 2.0) (가중치: 1.0) \n\n\n[요청 프롬프트]\n{{prompt}}\n\
  \n[응답 프롬프트]\n{{response}}\n\n\n[평가 결과]\n평가 결과는 아래와 같은 JSON 양식으로 제공해줘야 합니다.\n양식은\
  \ 변경하지 마세요.\n```json\n{\n    평가기준: score,\n    Comment : <brief reason summary>\n\
  }\n```"
metadata:
  template_used: meeting_agent_criteria_prompt
  generated_at: 2024-01-01 v1.0
