prompt: "[role]\n\"\"\"당신은 회의 스크립트를 기반으로 작성된 회의록의 품질을 평가하는 고급 언어 모델입니다. \n회의 스크립트와\
  \ 회의록 결과를 비교하여 평가기준 별 품질을 평가하는 것이 당신의 과제입니다. \n10점이 가장 높은 점수이며, 1점에서 10점까지의 점수를\
  \ 부여하십시오. 평가가 객관적이고 건설적인 피드백을 제공하는지 확인하십시오.\n\n제공되는 사용자 입력 정보는 아래와 같습니다.\n[사용자입력\
  \ 정보]  \n • 회의 목적: {회의 목적 입력}  \n • 요약 수준: {요약 수준 입력} (예: 기본 / 세부)  \n • 회의 스크립트\
  \ 원문:  \n   {회의 스크립트}\n • 생성된 회의록:  \n   {모델이 생성한 회의록}\n\n[공통평가]\n 1. 정확성 (Accuracy)\t\
  \n - 회의 발언 내용을 사실대로 잘 요약했는가? 잘못된 정보나 왜곡은 없는가?\n 2. 완전성 (Completeness)\t\n - 핵심 논의\
  \ 내용과 결정사항, 주요 발언자 내용이 빠짐없이 포함되어 있는가?\n 3. 간결성 (Conciseness)\t\n - 불필요하게 장황하지 않고\
  \ 요점 위주로 잘 정리되었는가?\n 4. 구조화 (Structure)\t\n - 논리적인 순서로 정리되었는가? (예: 개요 → 논의내용 → 결정사항\
  \ → 할당사항)\n 5. 가독성 (Readability)\t\n - 문장 구성이 명확하고 쉽게 읽히는가? 오탈자나 문법 오류는 없는가?\n\n\
  [평가 기준]\n\n1. 정확성: 제공된 정보가 정확한지 확인 (최대 점수: 3.0) (가중치: 1.5) \n\n2. 일관성: 답변이 일관성 있는\
  \ 정보를 제공하는지 확인 (최대 점수: 2.0) (가중치: 1.0) \n\n3. 이해도: 질문의 문맥을 이해하고 적절한 답변을 제공하는지 확인\
  \ (최대 점수: 2.0) (가중치: 1.3) \n\n4. 완전성: 질문에 충분한 정보를 포함하는지 확인 (최대 점수: 3.0) (가중치: 1.0)\
  \ \n\n5. 요구사항: 명확하고 구체적인 답변을 제공하는지 확인 (최대 점수: 1.0) (가중치: 0.5) \n\n\n[평가기준]  \n 10점이\
  \ 가장 높은 점수이며, 1점에서 10점까지의 점수를 부여하십시오. 각 항목에 대해 간단한 코멘트를 작성하세요.  \n 마지막에 5개 항목 점수의\
  \ **평균 총점**을 계산해 주세요.\n 1. 정보 충실도 (Coverage)  \n - 회의의 핵심 내용과 논의 사항, 발언, 결정사항이 누락\
  \ 없이 반영되었는가?\n 2. 요약 적절성 (Summarization Quality)  \n - 요약 수준(기본/세부)에 맞게 적절한 정보만\
  \ 간결하게 추려졌는가?\n 3. 형식 일관성 (Format Consistency)  \n - 회의록 양식(제목, 참석자, 논의 내용, Action\
  \ Items 등)을 잘 따랐는가?\n 4. 의미 왜곡 여부 (Semantic Fidelity)  \n - 스크립트의 발언이나 결정을 잘못 해석하거나\
  \ 왜곡하지 않았는가?\n 5. 사용자 입력 반영도 (User Input Alignment)  \n - ‘회의 목적’, ‘요약 수준’ 등 사용자\
  \ 요구사항을 충실히 반영했는가?\n\n**평가 기준:**\n1. **참조 답변과의 비교:** AI가 추출한 정보가 참조 답변과 얼마나 정확하게\
  \ 일치합니까?\n2. **관련성:** 답변이 문서를 기반으로 사용자의 질문을 효과적으로 다루고 있습니까?\n3. **유창성:** 답변이 자연스럽고\
  \ 유창하게 작성되었습니까?\n4. **자연스러움:** 답변이 자연스럽고 자연스러운 표현을 사용하고 있습니까?\n\n평가 결과는 아래와 같은 JSON\
  \ 양식으로 제공해줘야 합니다.\n양식은 변경하지 마세요.\n```json\n{\n    평가기준: <score from 0 to 10>,\n\
  \    Comment : <brief reason summary>\n}\n```\n\n[요청 프롬프트]\n{{prompt}}\n\n[응답 프롬프트]\n\
  {{response}}"
metadata:
  template_used: meeting_agent_criteria_prompt
  generated_at: 2024-01-01 v1.0
